version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: vtc-mongodb
    # ports:
    #   - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - kasm_default_network  # Use a custom network instead of network_mode
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  email-server:
    depends_on:
      mongodb:
        condition: service_healthy
    image: registry.gitlab.com/typaza/vtc-backend:latest
    container_name:	vtc-backend-dev
    pull_policy: always
    # ports:
    #   - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - EMAIL_PROVIDER=resend
      - EMAIL_USER='testmailcsharp2@gmail.com'
      - EMAIL_PASS='kkiq ydpd jnfo fkfg'
      - DRIVER_EMAIL="vtcjronde.contact@gmail.com" #  benharizmohamed@gmail.com
      - DRIVER_PHONE_NUMBER=33788968918 # +33788968918 33756826614
      - MONGODB_URI=mongodb://mongodb:27017/vtc-bookings
      - RESEND_API_KEY=re_KwUTHQ83_7btDUXcyPTW62d3anci6Bn2x
      - RESEND_FROM_EMAIL=reservation@vtc-jronde.com
    restart: unless-stopped
    networks:
      - kasm_default_network  # Use a custom network instead of network_mode
    # For production, you might want to add healthcheck
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  mongodb_data:

networks:
  kasm_default_network:
    external: true