# .devcontainer/Dockerfile
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:18

# Install any additional dependencies
RUN apt-get update && apt-get install -y \
    sudo \
    vim \
    wget \
    && apt-get clean


